In [1]:
import numpy as np 
import torch

In [2]:
np.set_printoptions(precision=3)


a = [1,2,3]

b = np.array([4,5,6])

t_a = torch.tensor(a)

t_b = torch.from_numpy(b)

t_a , t_b

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [8]:
t_ones = torch.ones(2,3)

t_ones, t_ones.shape

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([2, 3]))

In [19]:
rand_tensor = torch.rand(3,5)
rand_tensor

tensor([[0.2125, 0.9082, 0.4951],
        [0.0951, 0.0874, 0.6193]])

In [14]:
t_a_new = t_a.to(torch.int64)

t_a_new, t_a

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [23]:
t = torch.rand(3,5)
t_tr = torch.transpose(t,0,1)

print(f'{t} ---> \n{t_tr}')

tensor([[0.4388, 0.9716, 0.0677, 0.6803, 0.1917],
        [0.9296, 0.7789, 0.9916, 0.6383, 0.1866],
        [0.9067, 0.2219, 0.3946, 0.9477, 0.1024]]) ---> 
tensor([[0.4388, 0.9296, 0.9067],
        [0.9716, 0.7789, 0.2219],
        [0.0677, 0.9916, 0.3946],
        [0.6803, 0.6383, 0.9477],
        [0.1917, 0.1866, 0.1024]])


In [27]:
t_zeros = torch.zeros(30)

t_zeros_reshape = t_zeros.reshape(5,6)

t_zeros.shape , t_zeros_reshape.shape

(torch.Size([30]), torch.Size([5, 6]))

In [35]:
t = torch.zeros(1,2,1,4,1)

t_sqz = torch.squeeze(t,2)

t.shape , t_sqz.shape

(torch.Size([1, 2, 1, 4, 1]), torch.Size([1, 2, 4, 1]))

In [36]:
torch.manual_seed(1)


t1 = 2 * torch.rand(5,2) -1

t2 = torch.normal(mean=0,std=1,size=(5,2))

t3 = torch.multiply(t1,t2)

t3

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])